config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :reports, only: [:index] do
      collection do
        get :export_to_quickbooks
        post :export_to_quickbooks
      end
    end
  end
end

app/controllers/spree/admin/reports_controller_decorator.rb
require 'csv'

Spree::Admin::ReportsController.class_eval do

  Spree::Admin::ReportsController.add_available_report!(:export_to_quickbooks)

  def export_to_quickbooks
    # params[:q] = {} unless params[:q]

    # params[:q][:completed_at_gt] = if params[:q][:completed_at_gt].blank?
    #                                  Time.zone.now.beginning_of_month
    #                                else
    #                                  begin
    #                                    Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day
    #                                  rescue StandardError
    #                                    Time.zone.now.beginning_of_month
    #                                  end
    #                                end

    # if params[:q] && !params[:q][:completed_at_lt].blank?
    #   params[:q][:completed_at_lt] = begin
    #                                    Time.zone.parse(params[:q][:completed_at_lt]).end_of_day
    #                                  rescue StandardError
    #                                    ''
    #                                  end
    # end

    # params[:q][:s] ||= 'completed_at desc'

    # @search = Order.complete.ransack(params[:q])
    # @orders = @search.result

    @products = Spree::Product.all

    respond_to do |format|
      format.html
      format.csv do
        attributes = %w{name sku type inventory price}

        csv_output = CSV.generate(headers: true) do |csv|
          csv << attributes

          @products.each do |product|
            product.variants.each do |variant|
              csv << [variant.name,
                      variant.sku,
                      variant.tax_category.try(:name),
                      variant.total_on_hand,
                      variant.price]
            end
          end
        end

        send_data csv_output, filename: "QuickBooks-#{Date.today}.csv"
      end
    end

    # @totals = {}
    # @products.each do |order|
    #   @totals[order.currency] = { item_total: ::Money.new(0, order.currency), adjustment_total: ::Money.new(0, order.currency), sales_total: ::Money.new(0, order.currency) } unless @totals[order.currency]
    #   @totals[order.currency][:item_total] += order.display_item_total.money
    #   @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
    #   @totals[order.currency][:sales_total] += order.display_total.money
    # end
  end


end

app/views/spree/admin/reports/export_to_quickbooks.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:reports), spree.admin_reports_url %> /
  <%= "Export to QuickBooks" %>
<% end %>

<a class="btn btn-primary pull-right" href="<%= export_to_quickbooks_admin_reports_path %>.csv">Export to CSV</a>
<div class="clearfix"></div>
<br>

<table class="table table-bordered admin-report" data-hook="export_to_quickbooks">
  <thead>
    <tr>
      <th><%= "Product/Service Name" %></th>
      <th><%= "SKU" %></th>
      <th><%= "Type" %></th>
      <th><%= "Inventory" %></th>
      <th><%= "Sales Price/Rate" %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <% product.variants.each do |variant| %>
        <tr>
          <td><%= "#{variant.name} (#{variant.options_name})" %></td>
          <td><%= variant.sku %></td>
          <td><%= variant.tax_category.try(:name) %></td>
          <td><%= variant.total_on_hand %></td>
          <td><%= humanized_money_with_symbol variant.price %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>